from __future__ import annotations

import json
import os
import sqlite3
from contextlib import contextmanager
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any, Iterator

from .security import hash_password, verify_password


ROOT = Path(__file__).resolve().parents[1]
DATABASE_URL = os.environ.get("DATABASE_URL")
DB_PATH = Path(os.environ.get("DB_PATH", ROOT / "data" / "app.db"))
LESSONS_PATH = ROOT / "content" / "lessons.json"
MISCONCEPTION_QUESTIONS_PATH = ROOT / "content" / "misconception_questions.json"


def utcnow() -> str:
    return datetime.now(UTC).isoformat()


class Database:
    def __init__(self, connection: Any, backend: str) -> None:
        self.connection = connection
        self.backend = backend

    def execute(self, query: str, params: tuple[Any, ...] = ()) -> Any:
        if self.backend == "postgres":
            query = query.replace("?", "%s")
        return self.connection.execute(query, params)

    def commit(self) -> None:
        self.connection.commit()

    def close(self) -> None:
        self.connection.close()


def is_postgres() -> bool:
    return bool(DATABASE_URL)


def is_production() -> bool:
    return os.environ.get("APP_ENV") == "production"


def string_agg_expr(value: str) -> str:
    if is_postgres():
        return f"STRING_AGG({value}, ',')"
    return f"GROUP_CONCAT({value})"


def connect() -> Database:
    if DATABASE_URL:
        import psycopg
        from psycopg.rows import dict_row

        return Database(psycopg.connect(DATABASE_URL, row_factory=dict_row), "postgres")

    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return Database(conn, "sqlite")


@contextmanager
def get_db() -> Iterator[Database]:
    conn = connect()
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def schema_statements() -> list[str]:
    user_id = "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if is_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    attempt_id = (
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if is_postgres()
        else "id INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    return [
        f"""
        CREATE TABLE IF NOT EXISTS users (
            {user_id},
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL CHECK(role IN ('student', 'admin')),
            display_name TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS sessions (
            token TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            expires_at TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS questions (
            id TEXT PRIMARY KEY,
            source_file TEXT NOT NULL,
            type TEXT NOT NULL,
            difficulty INTEGER NOT NULL,
            stem TEXT NOT NULL,
            code TEXT NOT NULL DEFAULT '',
            options_json TEXT NOT NULL,
            answer_json TEXT NOT NULL,
            explanation TEXT NOT NULL,
            common_mistake TEXT NOT NULL,
            is_active INTEGER NOT NULL DEFAULT 1
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS concepts (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            unit TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT ''
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS lessons (
            id TEXT PRIMARY KEY,
            source_file TEXT NOT NULL,
            unit TEXT NOT NULL,
            title TEXT NOT NULL,
            order_index INTEGER NOT NULL,
            content_json TEXT NOT NULL,
            goals_json TEXT NOT NULL,
            common_mistakes_json TEXT NOT NULL,
            checkpoint_question_ids_json TEXT NOT NULL,
            is_active INTEGER NOT NULL DEFAULT 1
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS question_concepts (
            question_id TEXT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
            concept_id TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
            weight REAL NOT NULL DEFAULT 1.0,
            PRIMARY KEY (question_id, concept_id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS lesson_concepts (
            lesson_id TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
            concept_id TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
            PRIMARY KEY (lesson_id, concept_id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS lesson_progress (
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            lesson_id TEXT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
            status TEXT NOT NULL DEFAULT 'not_started'
                CHECK(status IN ('not_started', 'in_progress', 'completed')),
            last_viewed_at TEXT,
            completed_at TEXT,
            checkpoint_correct_count INTEGER NOT NULL DEFAULT 0,
            checkpoint_total_count INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (user_id, lesson_id)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS attempts (
            {attempt_id},
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            question_id TEXT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
            selected_answer_json TEXT NOT NULL,
            is_correct INTEGER NOT NULL,
            used_hint INTEGER NOT NULL DEFAULT 0,
            ran_code INTEGER NOT NULL DEFAULT 0,
            elapsed_seconds INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS review_sessions (
            {attempt_id},
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            started_at TEXT NOT NULL,
            last_answered_at TEXT,
            answered_count INTEGER NOT NULL DEFAULT 0,
            correct_count INTEGER NOT NULL DEFAULT 0,
            completed_at TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS concept_mastery (
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            concept_id TEXT NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
            mastery_score INTEGER NOT NULL DEFAULT 50,
            last_practiced_at TEXT,
            wrong_streak INTEGER NOT NULL DEFAULT 0,
            correct_streak INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (user_id, concept_id)
        )
        """,
    ]


def init_db() -> None:
    with get_db() as db:
        for statement in schema_statements():
            db.execute(statement)

    seed_questions()
    seed_lessons()
    seed_users()


def concept_name(concept_id: str) -> str:
    return concept_id.replace("-", " ")


def unit_from_source(source_file: str) -> str:
    if source_file.startswith("01-"):
        return "第 1 講"
    if source_file.startswith("02-"):
        return "第 2 講"
    if source_file.startswith("03-"):
        return "第 3 講"
    if source_file.startswith("04-"):
        return "第 4 講"
    if source_file.startswith("05-"):
        return "第 5 講"
    if source_file.startswith("06-"):
        return "第 6 講"
    if source_file.startswith("07-"):
        return "第 7 講"
    if source_file.startswith("08-"):
        return "第 8 講"
    if source_file.startswith("09-"):
        return "第 9 講"
    if source_file.startswith("10-"):
        return "第 10 講"
    return ""


def load_questions() -> list[dict[str, Any]]:
    questions: list[dict[str, Any]] = []
    for path in sorted((ROOT / "content").glob("questions*.json")):
        questions.extend(json.loads(path.read_text(encoding="utf-8")))
    return questions


def load_misconception_question_ids() -> set[str]:
    mappings = json.loads(MISCONCEPTION_QUESTIONS_PATH.read_text(encoding="utf-8"))
    return {
        question_id
        for lesson_mappings in mappings.values()
        for question_ids in lesson_mappings
        for question_id in question_ids
    }


def seed_questions() -> None:
    questions = load_questions()
    with get_db() as db:
        for question in questions:
            db.execute(
                """
                INSERT INTO questions (
                    id, source_file, type, difficulty, stem, code, options_json,
                    answer_json, explanation, common_mistake, is_active
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
                ON CONFLICT(id) DO UPDATE SET
                    source_file=excluded.source_file,
                    type=excluded.type,
                    difficulty=excluded.difficulty,
                    stem=excluded.stem,
                    code=excluded.code,
                    options_json=excluded.options_json,
                    answer_json=excluded.answer_json,
                    explanation=excluded.explanation,
                    common_mistake=excluded.common_mistake,
                    is_active=1
                """,
                (
                    question["id"],
                    question["source_file"],
                    question["type"],
                    question["difficulty"],
                    question["stem"],
                    question.get("code", ""),
                    json.dumps(question["options"], ensure_ascii=False),
                    json.dumps(question["answer"], ensure_ascii=False),
                    question["explanation"],
                    question["common_mistake"],
                ),
            )
            db.execute("DELETE FROM question_concepts WHERE question_id = ?", (question["id"],))
            for concept_id in question["concepts"]:
                db.execute(
                    """
                    INSERT INTO concepts (id, name, unit, description)
                    VALUES (?, ?, ?, '')
                    ON CONFLICT(id) DO UPDATE SET
                        name=excluded.name,
                        unit=CASE WHEN concepts.unit = '' THEN excluded.unit ELSE concepts.unit END
                    """,
                    (concept_id, concept_name(concept_id), unit_from_source(question["source_file"])),
                )
                db.execute(
                    "INSERT INTO question_concepts (question_id, concept_id, weight) VALUES (?, ?, 1.0)",
                    (question["id"], concept_id),
                )


def seed_lessons() -> None:
    lessons = json.loads(LESSONS_PATH.read_text(encoding="utf-8"))
    with get_db() as db:
        for lesson in lessons:
            db.execute(
                """
                INSERT INTO lessons (
                    id, source_file, unit, title, order_index, content_json,
                    goals_json, common_mistakes_json, checkpoint_question_ids_json, is_active
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
                ON CONFLICT(id) DO UPDATE SET
                    source_file=excluded.source_file,
                    unit=excluded.unit,
                    title=excluded.title,
                    order_index=excluded.order_index,
                    content_json=excluded.content_json,
                    goals_json=excluded.goals_json,
                    common_mistakes_json=excluded.common_mistakes_json,
                    checkpoint_question_ids_json=excluded.checkpoint_question_ids_json,
                    is_active=1
                """,
                (
                    lesson["id"],
                    lesson["source_file"],
                    lesson["unit"],
                    lesson["title"],
                    lesson["order"],
                    json.dumps(lesson["body"], ensure_ascii=False),
                    json.dumps(lesson["goals"], ensure_ascii=False),
                    json.dumps(lesson["common_mistakes"], ensure_ascii=False),
                    json.dumps(lesson["checkpoint_question_ids"], ensure_ascii=False),
                ),
            )
            db.execute("DELETE FROM lesson_concepts WHERE lesson_id = ?", (lesson["id"],))
            for concept_id in lesson["concepts"]:
                db.execute(
                    """
                    INSERT INTO concepts (id, name, unit, description)
                    VALUES (?, ?, ?, '')
                    ON CONFLICT(id) DO UPDATE SET
                        name=excluded.name,
                        unit=CASE WHEN concepts.unit = '' THEN excluded.unit ELSE concepts.unit END
                    """,
                    (concept_id, concept_name(concept_id), lesson["unit"]),
                )
                db.execute(
                    "INSERT INTO lesson_concepts (lesson_id, concept_id) VALUES (?, ?)",
                    (lesson["id"], concept_id),
                )


def seed_user_configs() -> list[dict[str, str]]:
    return [
        {
            "username": os.environ.get("ADMIN_USERNAME", "admin"),
            "password": os.environ.get("ADMIN_PASSWORD", "admin123"),
            "password_key": "ADMIN_PASSWORD",
            "default_password": "admin123",
            "role": "admin",
            "display_name": "管理者",
        },
        {
            "username": os.environ.get("STUDENT1_USERNAME", "student1"),
            "password": os.environ.get("STUDENT1_PASSWORD", "student123"),
            "password_key": "STUDENT1_PASSWORD",
            "default_password": "student123",
            "role": "student",
            "display_name": "柚子",
        },
        {
            "username": os.environ.get("STUDENT2_USERNAME", "student2"),
            "password": os.environ.get("STUDENT2_PASSWORD", "student123"),
            "password_key": "STUDENT2_PASSWORD",
            "default_password": "student123",
            "role": "student",
            "display_name": "嫺嫺",
        },
    ]


def seed_users() -> None:
    configs = seed_user_configs()
    with get_db() as db:
        for config in configs:
            if is_production() and config["password_key"] not in os.environ:
                continue
            exists = db.execute("SELECT * FROM users WHERE username = ?", (config["username"],)).fetchone()
            if exists:
                password_changed = config["password_key"] in os.environ and not verify_password(
                    config["password"], exists["password_hash"]
                )
                profile_changed = exists["role"] != config["role"] or exists["display_name"] != config["display_name"]
                if password_changed or profile_changed:
                    db.execute(
                        """
                        UPDATE users
                        SET password_hash = ?, role = ?, display_name = ?
                        WHERE username = ?
                        """,
                        (
                            hash_password(config["password"]) if password_changed else exists["password_hash"],
                            config["role"],
                            config["display_name"],
                            config["username"],
                        ),
                    )
                continue
            db.execute(
                """
                INSERT INTO users (username, password_hash, role, display_name, created_at)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    config["username"],
                    hash_password(config["password"]),
                    config["role"],
                    config["display_name"],
                    utcnow(),
                ),
            )


def session_expiry() -> str:
    return (datetime.now(UTC) + timedelta(days=7)).isoformat()
